<template>
<view class="panel content-card post-workbench">
            <view class="section-head"><text>成品视频</text><view class="actions"><button v-if="current.has_raw_video" class="ghost small" @click="$emit('download','video_raw')">下载无字幕原片</button><button v-if="current.has_subtitle_video" class="ghost small" @click="$emit('download','video_subtitled')">下载字幕版</button><button v-if="current.has_bgm_video" class="ghost small" @click="$emit('download','video_bgm')">下载配乐成片</button></view></view>
            <view v-if="!videoSource" class="video-lazy"><text class="video-lazy-title">视频尚未加载</text><text class="hint">切换项目不会下载视频，点击播放后才开始加载。</text><view class="actions"><button class="primary small" @click="$emit('load-video','video')">播放{{ current.has_bgm_video ? '配乐版' : '视频' }}</button><button v-if="current.has_raw_video&&current.has_bgm_video" class="ghost small" @click="$emit('load-video','video_raw')">播放无配乐版</button></view></view><video v-else class="video" :src="videoSource" controls autoplay @error="$emit('video-error')"></video>
            <view v-if="current.has_raw_video" class="subtitle-settings subtitle-editor">
              <view class="post-accordion">
                <view class="post-accordion-head" @click="$emit('toggle-panel','title')"><view><text class="auto-run-title">视频上方标题</text><text class="hint">最多三行，可在成片后单独开启或调整</text></view><view class="accordion-meta"><text class="accordion-status" :class="{enabled:current.video_title_enabled}">{{ isBusy ? '处理中' : (current.video_title_enabled ? '已开启' : '未开启') }}</text><text class="accordion-arrow">{{ postPanels.title ? '▲' : '▼' }}</text></view></view>
                <view v-if="postPanels.title" class="post-accordion-body">
              <view class="subtitle-preset-bar"><view><text class="auto-run-title">视频号顶部标题</text><text class="hint">标题和字幕会一起加入成片，避免重复处理视频</text></view><button class="ghost small" @click="$emit('apply-title-preset')">应用预设</button></view>
              <checkbox-group @change="$emit('set-title-enabled',$event)"><label class="compact-check"><checkbox value="title" :checked="current.video_title_enabled" color="#d7ff68" /><text>启用视频顶部常驻标题</text></label></checkbox-group>
              <view v-if="current.video_title_enabled" class="video-title-editor"><view><text class="label">标题文案（最多三行，每行12字）</text><textarea v-model="current.video_title" class="textarea video-title-input" :maxlength="100"></textarea><button class="ghost small title-regenerate" @click="current.video_title=suggestVideoTitleText(current.script||current.original_script)">从口播稿重新提取</button></view><view class="subtitle-grid"><view><text class="label">字体</text><picker :range="fontOptions" @change="current.video_title_font_name=fontOptions[$event.detail.value]"><view class="field picker-field">{{ current.video_title_font_name }}</view></picker></view><view><text class="label">字号 {{ Number(current.video_title_font_size||88) }}</text><slider :value="Number(current.video_title_font_size||88)" min="48" max="140" step="1" activeColor="#d7ff68" block-size="14" @changing="current.video_title_font_size=$event.detail.value"/></view><view><text class="label">距顶部 {{ Number(current.video_title_position||10) }}%</text><slider :value="Number(current.video_title_position||10)" min="3" max="35" step="1" activeColor="#d7ff68" block-size="14" @changing="current.video_title_position=$event.detail.value"/></view><view><text class="label">黑色描边 {{ Number(current.video_title_stroke_width||4) }}</text><slider :value="Number(current.video_title_stroke_width||4)" min="0" max="8" step="0.5" activeColor="#d7ff68" block-size="14" @changing="current.video_title_stroke_width=$event.detail.value"/></view><view><text class="label">标题颜色</text><input v-model="current.video_title_primary_color" class="field color-field" maxlength="7" /></view></view></view>
                </view>
              </view>
              <view class="post-accordion">
                <view class="post-accordion-head" @click="$emit('toggle-panel','subtitle')"><view><text class="auto-run-title">口播字幕</text><text class="hint">可在成片后开启，不会重新生成数字人视频</text></view><view class="accordion-meta"><text class="accordion-status" :class="{enabled:current.subtitle_enabled}">{{ isBusy ? '处理中' : (current.subtitle_enabled ? '已开启' : '未开启') }}</text><text class="accordion-arrow">{{ postPanels.subtitle ? '▲' : '▼' }}</text></view></view>
                <view v-if="postPanels.subtitle" class="post-accordion-body">
              <view v-if="current.subtitle_enabled" class="subtitle-preset-bar"><view><text class="auto-run-title">视频号口播字幕</text><text class="hint">应用后点击下方按钮重新生成字幕版</text></view><button class="ghost small" @click="$emit('apply-subtitle-preset')">应用预设</button></view>
              <checkbox-group @change="$emit('set-subtitle-enabled',$event)"><label class="compact-check"><checkbox value="subtitle" :checked="current.subtitle_enabled" color="#d7ff68" /><text>启用成片字幕</text></label></checkbox-group>
              <view v-if="current.subtitle_enabled" class="subtitle-grid">
                <view><text class="label">字体</text><picker :range="fontOptions" @change="current.subtitle_font_name=fontOptions[$event.detail.value]"><view class="field picker-field">{{ current.subtitle_font_name }}</view></picker></view>
                <checkbox-group @change="$emit('set-subtitle-bold',$event)"><label class="compact-check subtitle-bold"><checkbox value="bold" :checked="current.subtitle_font_bold" color="#d7ff68" /><text>粗体字幕</text></label></checkbox-group>
                <view><text class="label">位置</text><view class="position-options"><button v-for="item in subtitlePositions" :key="`current-${item.value}`" class="position-button" :class="{active:current.subtitle_position===item.value}" @click="current.subtitle_position=item.value">{{ item.label }}</button></view></view>
                <view v-if="current.subtitle_position==='custom'"><text class="label">距顶部 {{ Number(current.subtitle_custom_position||0) }}%</text><slider :value="Number(current.subtitle_custom_position||0)" min="0" max="100" step="1" activeColor="#d7ff68" block-size="14" @changing="current.subtitle_custom_position=$event.detail.value"/></view>
                <view><text class="label">字号 {{ Number(current.subtitle_font_size||60) }}</text><slider :value="Number(current.subtitle_font_size||60)" min="20" max="100" step="1" activeColor="#d7ff68" block-size="14" @changing="current.subtitle_font_size=$event.detail.value"/></view>
                <view><text class="label">单条最大字数</text><input v-model="current.subtitle_max_chars" class="field" type="number" /></view>
                <view><text class="label">文字颜色（#RRGGBB）</text><input v-model="current.subtitle_font_color" class="field color-field" maxlength="7" /><view class="color-options"><button v-for="color in subtitleColors" :key="`current-${color}`" class="color-swatch" :class="{active:String(current.subtitle_font_color||'').toUpperCase()===color}" :style="{backgroundColor:color}" :title="color" @click="current.subtitle_font_color=color"></button></view></view>
                <view><text class="label">黑色描边 {{ Number(current.subtitle_stroke_width||0) }}</text><slider :value="Number(current.subtitle_stroke_width||0)" min="0" max="8" step="0.5" activeColor="#d7ff68" block-size="14" @changing="current.subtitle_stroke_width=$event.detail.value"/></view>
              </view>
              <checkbox-group v-if="current.subtitle_enabled" @change="$emit('set-subtitle-background',$event)"><label class="compact-check"><checkbox value="background" :checked="current.subtitle_background_enabled" color="#d7ff68" /><text>显示半透明字幕背景</text></label></checkbox-group>
              <view v-if="current.subtitle_enabled&&current.subtitle_background_enabled" class="subtitle-grid"><view><text class="label">背景颜色</text><input v-model="current.subtitle_background_color" class="field color-field" maxlength="7" /></view><view><text class="label">背景不透明度 {{ Number(current.subtitle_background_opacity||0) }}%</text><slider :value="Number(current.subtitle_background_opacity||0)" min="0" max="100" step="1" activeColor="#d7ff68" block-size="14" @changing="current.subtitle_background_opacity=$event.detail.value"/></view></view>
                </view>
              </view>
              <view v-if="current.subtitle_enabled||current.video_title_enabled" class="subtitle-preview-frame"><image v-if="current.has_image" class="subtitle-preview-image" :src="imageUrl" mode="aspectFill"/><view class="subtitle-safe-zone">视频号界面安全区</view><view v-if="current.video_title_enabled" class="video-title-preview" :style="videoTitlePositionStyle(current)"><text v-for="(line,index) in videoTitleLines(current.video_title)" :key="`current-title-${index}`" :style="videoTitleLineStyle(current,index)">{{ line }}</text></view><view v-if="current.subtitle_enabled" class="subtitle-preview-text" :style="[subtitlePreviewStyle(current),subtitlePreviewPositionStyle(current)]"><text>{{ String(current.script||current.original_script||'字幕效果预览').slice(0, Number(current.subtitle_max_chars||14)) }}</text></view></view>
              <button class="primary wide" :disabled="isBusy" @click="$emit('save-subtitle')">{{ (current.subtitle_enabled||current.video_title_enabled) ? (current.has_subtitle_video ? '重新生成标题/字幕版' : '生成标题/字幕版') : '保存并关闭标题与字幕' }}</button>
            </view>
            <view v-if="current.has_raw_video" class="bgm-editor">
              <view class="section-head"><view><text class="subheading quality-title">背景音乐后期</text><text class="hint inline-hint">更换或调整配乐不会重新生成数字人视频</text></view><button class="ghost small" @click="$emit('choose-bgm')">更换音乐</button></view>
              <view><text class="label">配乐音量 {{ Math.round(Number(current.bgm_volume || 0) * 100) }}%</text><slider :value="Number(current.bgm_volume || 0) * 100" min="0" max="100" step="1" activeColor="#d7ff68" block-size="14" @changing="current.bgm_volume=$event.detail.value/100"/></view>
              <checkbox-group @change="$emit('set-bgm-ducking',$event)"><label class="compact-check"><checkbox value="duck" :checked="current.bgm_ducking" color="#d7ff68" /><text>人声出现时自动降低配乐</text></label></checkbox-group>
              <view class="bgm-times"><view><text class="label">淡入秒数</text><input v-model="current.bgm_fade_in" class="field" type="digit" /></view><view><text class="label">淡出秒数</text><input v-model="current.bgm_fade_out" class="field" type="digit" /></view></view>
              <button class="primary wide" :disabled="isBusy||!current.has_bgm" @click="$emit('save-bgm')">{{ current.has_bgm_video ? '重新生成配乐版' : '生成配乐版' }}</button>
            </view>
          </view>
</template>

<script>
export default {
  name:'PostEditor',
  props:{current:{type:Object,required:true},videoSource:{type:String,default:''},isBusy:Boolean,postPanels:{type:Object,required:true},fontOptions:{type:Array,default:()=>[]},subtitleColors:{type:Array,default:()=>[]},subtitlePositions:{type:Array,default:()=>[]},imageUrl:{type:String,default:''}},
  emits:['download','load-video','video-error','toggle-panel','apply-title-preset','set-title-enabled','apply-subtitle-preset','set-subtitle-enabled','set-subtitle-bold','set-subtitle-background','save-subtitle','choose-bgm','set-bgm-ducking','save-bgm'],
  methods:{
    suggestVideoTitleText(script){const text=String(script||'').replace(/\s+/g,'').trim();if(!text)return '';const sentences=text.split(/[\u3002\uff01\uff1f!?]+/).filter(Boolean),first=sentences[0]||text,clauses=first.split(/[\uff0c,\uff1b;]/).map(item=>item.trim()).filter(Boolean);let lines=clauses.slice(0,3);if(lines.length===1&&lines[0].length>12){const value=lines[0];lines=[];for(let offset=0;offset<Math.min(value.length,36);offset+=12)lines.push(value.slice(offset,offset+12))}if(lines.length===1&&sentences.length>1)lines.push(...sentences.slice(1,3));return lines.slice(0,3).map(line=>line.slice(0,12)).join('\n')},
    videoTitleLines(value){const lines=[];for(const raw of String(value||'').replace(/\r/g,'').split('\n')){let line=raw.replace(/\s+/g,'');while(line&&lines.length<3){lines.push(line.slice(0,12));line=line.slice(12)}if(lines.length>=3)break}return lines.length?lines:['\u89c6\u9891\u6807\u9898']},
    videoTitlePositionStyle(value){return {top:`${Math.max(3,Math.min(35,Number(value?.video_title_position??10)))}%`}},
    videoTitleLineStyle(value){const width=Math.max(0,Number(value?.video_title_stroke_width??4)/4.5),stroke=String(value?.video_title_stroke_color||'#000000');return {display:'block',fontFamily:String(value?.video_title_font_name||'sans-serif'),fontSize:`${Math.max(14,Number(value?.video_title_font_size||88)/4.5)}px`,fontWeight:'800',lineHeight:'1.2',color:String(value?.video_title_primary_color||'#FFFFFF'),WebkitTextStroke:width?`${width}px ${stroke}`:'0',paintOrder:'stroke fill'}},
    subtitlePreviewPositionStyle(value){const position=String(value?.subtitle_position||'custom'),top=position==='top'?14:position==='center'?50:position==='bottom'?76:Number(value?.subtitle_custom_position??73);return {top:`${Math.max(5,Math.min(90,top))}%`}},
    subtitlePreviewStyle(value){const hex=String(value?.subtitle_background_color||'#000000'),alpha=Math.max(0,Math.min(1,Number(value?.subtitle_background_opacity||0)/100)),rgb=/^#[0-9a-fA-F]{6}$/.test(hex)?`${parseInt(hex.slice(1,3),16)},${parseInt(hex.slice(3,5),16)},${parseInt(hex.slice(5,7),16)}`:'0,0,0',strokeWidth=Math.max(0,Number(value?.subtitle_stroke_width??3)/4.5),stroke=String(value?.subtitle_stroke_color||'#000000');return {fontFamily:String(value?.subtitle_font_name||'sans-serif'),fontSize:`${Math.max(12,Number(value?.subtitle_font_size||64)/4.5)}px`,fontWeight:value?.subtitle_font_bold?'700':'400',color:String(value?.subtitle_font_color||'#FFFFFF'),WebkitTextStroke:strokeWidth?`${strokeWidth}px ${stroke}`:'0',paintOrder:'stroke fill',textShadow:'none',backgroundColor:value?.subtitle_background_enabled?`rgba(${rgb},${alpha})`:'transparent'}}
  }
}
</script>
