<template>
  <view class="queue-page">
    <view class="page-heading"><view><text class="eyebrow">PRODUCTION</text><text class="page-title">任务队列</text><text class="lead">只保留等待、运行、失败和已取消任务；完成项目自动进入项目库。<text class="realtime-state" :class="{online:realtimeConnected}">{{ realtimeConnected ? '状态已同步' : '正在恢复连接' }}</text></text></view><button class="ghost small" @click="$emit('refresh')">刷新</button></view>
    <view class="queue-stats"><view class="panel stat-card"><text class="stat-value">{{ runningCount }}</text><text class="hint">正在执行</text></view><view class="panel stat-card"><text class="stat-value">{{ queuedCount }}</text><text class="hint">等待中</text></view><view class="panel stat-card danger"><text class="stat-value">{{ failedCount }}</text><text class="hint">需要处理</text></view></view>
    <view v-if="!tasks.length" class="panel page-empty"><text class="empty-title">当前没有生产任务</text><text class="hint">新建任务并选择全自动制作后，会在这里看到执行状态。</text><button class="primary small" @click="$emit('create')">新建任务</button></view>
    <view v-else class="queue-list-main"><view v-for="task in tasks" :key="task.id" class="panel task-card-large" :class="`queue-${taskDisplayClass(task)}`" @click="$emit('open',task.project_id)"><view class="task-card-status"><text class="task-status-dot"></text><text>{{ statusName(task.display_status) }}</text></view><view class="task-card-content"><text class="task-card-title">{{ task.project_title }}</text><text class="hint">{{ taskStageName(task.stage) }} · {{ ttsEngineName(task.tts_engine) }}</text><view class="task-progress"><view :style="{width:`${Number(task.display_progress||0)}%`}"></view></view><view class="task-progress-copy"><text>{{ taskProgressText(task) }}</text><text>{{ Number(task.display_progress||0) }}%</text></view><text v-if="task.error" class="task-error-summary">{{ task.error.message || task.error }}</text></view><view class="task-card-actions"><button v-if="task.status==='QUEUED'||task.status==='RUNNING'" class="ghost small" @click.stop="$emit('cancel',task)">取消</button><button v-if="canRetryTask(task)" class="primary small" @click.stop="$emit('retry',task)">重试</button><button class="danger-button small" :disabled="task.deleting" @click.stop="$emit('delete',task)">{{ task.deleting ? '删除中' : '删除' }}</button></view></view></view>
  </view>
</template>

<script>
export default {name:'TaskQueuePage',props:{tasks:{type:Array,default:()=>[]},runningCount:Number,queuedCount:Number,failedCount:Number,realtimeConnected:Boolean,statusName:{type:Function,required:true},taskStageName:{type:Function,required:true},ttsEngineName:{type:Function,required:true},taskProgressText:{type:Function,required:true},taskDisplayClass:{type:Function,required:true},canRetryTask:{type:Function,required:true}},emits:['refresh','create','open','cancel','retry','delete']}
</script>
